# Function for getting data on team strength indicators for teams that have
# played in the Premier League since the 2016/17 season.
# ------------------------------------------------------------------------------
fetch_elo_data <- function(teams, from = "2016-08-01", to = lubridate::today()) {
  require(dplyr)
  require(purrr)
  require(stringr)
  require(readr)
  require(lubridate)
  
  # Function for calling the elo API to fetch data for a given team
  get_team_elo_data <- function(team_name, ...) {
    
    url <- "http://api.clubelo.com/"
    
    # Convert FPL-style team names to elo-style url path
    case_when(
      team_name == "West Bromwich Albion" ~ "WestBrom",
      team_name == "Man Utd" ~ "ManUnited",
      team_name == "Spurs" ~ "Tottenham",
      team_name == "Stoke City" ~ "Stoke",
      team_name == "Swansea City" ~ "Swansea",
      team_name == "Sheffield Utd" ~ "SheffieldUnited",
      team_name %>% str_detect(" ") ~ str_replace(team_name, " ", ""),
      TRUE ~ team_name
    ) %>% 
      paste0(url, .) %>% 
      read_csv(.) %>% 
      filter(From %within% interval(ymd(from), ymd(to))) %>% 
      mutate(team_name = team_name) %>% 
      select(team_name, elo = Elo, from = From, to = To) %>% 
      arrange(from)
  }
  
  # Apply the `get_elo_data` function to each team that appears in the table
  # generated by `gen_team_lookup_tbl`
  tibble(team_name = teams) %>% 
    mutate(data = map(team_name, ~ suppressMessages(get_team_elo_data(.x)))) %>% 
    pull(data) %>% 
    map_dfr(., ~rbind(.x)) %>% 
    arrange(team_name, from, to)
}


# Function for writing the latest elo dataset to disk
# ------------------------------------------------------------------------------
gen_elo_data_latest <- function(data_path = "..") {
  require(dplyr)
  require(jsonlite)
  require(readr)
  
  # Get team names appearing in vaastav, and current season
  teams_vaastav <- fromJSON(paste0(data_path, "/vaastav/previous_seasons_player_fixtures.json")) %>% 
    pull(team_name) %>% 
    unique()
  
  teams_fpl <- fromJSON(paste0(data_path, "/fpl/fpl_player_data_latest.json")) %>% 
    pull(team_name) %>% 
    unique()
  
  all_teams <- c(teams_vaastav, teams_fpl) %>% unique
  
  fetch_elo_data(all_teams) %>% 
    toJSON(., "rows") %>%
    write_file(., paste0(data_path, "/clubelo.com/elo_data_latest.json"))
} 
