```{r}
library(tidyverse)
library(lubridate)
library(mlr)
library(mlrHyperopt)
library(xgboost)
```


# Gen model data
```{r}
source("./func.R")
model_data <- gen_cs_model_data() %>% 
  filter(set == "train")
```

# Validation strategy and `mlr` task
```{r}
train <- which(model_data$kickoff_time %>% year() < 2019)
test <- which(model_data$kickoff_time %>% as.Date() %within% interval("2019-01-01", "2019-03-31"))
validation <- which(model_data$kickoff_time %>% as.Date() >= "2019-04-01")
blocker <- factor(model_data$team_name)

features <- c(
  "clean_sheet",
  "team_elo_strength", "elo_strength_diff",
  "was_home", "goals_conceded_smooth", "threat_smooth",
  "bps_smooth", "defense_tackles_smooth",
  "defense_tackled_smooth", "defense_saves_smooth",
  "opponent_goals_scored_smooth", "opponent_threat_smooth", "opponent_ict_index_smooth"
)

task_data <- model_data %>% select(features) %>% as.data.frame()

task <- makeClassifTask(
  data = task_data,
  target = "clean_sheet",
  positive = 1,
  blocking = blocker
)

train_task <- subsetTask(task, train)
test_task <- subsetTask(task, test)
validation_task <- subsetTask(task, validation)
```

# Tuning
```{r}
xgb_learner <- makeLearner(
  "classif.xgboost",
  predict.type = "prob",
  eval_metric = "auc",
  objective = "binary:logistic",
  eta = 0.2214595,
  nrounds = 168,
  max_depth = 1,
  colsample_bytree = 0.4367378,
  min_child_weight = 1.676057,
  subsample = 0.3964952,
  alpha = 2.721789,
  lambda = 4.282457,
  gamma = 4.45842,
  early_stopping_rounds = 17
)

autotune_config <- makeParConfig(
  par.set = makeParamSet(
    makeNumericParam("alpha", 0, 5),
    makeNumericParam("lambda", 1, 5),
    makeNumericParam("gamma", 0, 10),
    makeIntegerParam("early_stopping_rounds", 10, 30)
  )
)

autotune_res <- hyperopt(
  task = train_task,
  learner = xgb_learner,
  par.config = autotune_config
)

tuned_xgb_learner <- xgb_learner %>% setHyperPars(par.vals = autotune_res$x)

cv_res <- resample(
  learner = tuned_xgb_learner,
  task = train_task,
  resampling = makeResampleDesc("CV", blocking.cv = T, fixed = T, predict = "both"),
  measures = list(auc, setAggregation(auc, train.mean))
)

```

# Check feature importance
```{r}
model <- train(xgb_learner, train_task)
model %>% getFeatureImportance()
```

# Check validation scheme
```{r}
test_preds <- predict(model, test_task)
performance(test_preds, measure = auc)

model <- train(xgb_learner, subsetTask(task, c(train, test)))
validation_preds <- predict(model, validation_task)
performance(validation_preds, measure = auc)
```

